### ISSUE TITLE
won't build: missing chicken.platform

### ISSUE THREAD

**Issue by tuxick** [kdltr/ensemble#1]
running make gives me:
Error: (import) during expansion of (import ...) - cannot import from undefined module: chicken.platform
  
        Call history:
  
        <syntax>          (##core#require-extension (chicken.platform) #t)
        <syntax>          (##core#begin (##core#begin (##sys#require (quote chicken.platform)) (import chicken.platform)) (##c...
        <syntax>          (##core#begin (##sys#require (quote chicken.platform)) (import chicken.platform))
        <syntax>          (##sys#require (quote chicken.platform))
        <syntax>          (quote chicken.platform)
        <syntax>          (##core#quote chicken.platform)    
        <syntax>          (import chicken.platform)     <--

**Comment by kdltr** [comment]
Current master branch requires CHICKEN 5 to build, which is not not yet fully released (but release candidates are available)
